"""Added original_id

Revision ID: 0bb6648f80d6
Revises: fadea9fbe29e
Create Date: 2024-11-13 11:35:55.182715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bb6648f80d6'
down_revision = 'fadea9fbe29e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['original_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('original_id')

    # ### end Alembic commands ###
