"""Allow all columns to accept NULL values

Revision ID: 50e17fab3ad8
Revises: 6758bcecb8ed
Create Date: 2024-11-11 11:16:27.744411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50e17fab3ad8'
down_revision = '6758bcecb8ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('national_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('industry_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('group_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('in_market',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('in_market',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('group_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('industry_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('national_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
