"""seprated the tables

Revision ID: 5273143f5481
Revises: 0bb6648f80d6
Create Date: 2024-11-13 12:18:31.736129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5273143f5481'
down_revision = '0bb6648f80d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_original_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_original_id'], ['company.original_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_original_id')
    )
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('count')
        batch_op.drop_column('number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True))

    op.drop_table('status')
    # ### end Alembic commands ###
