"""remove items for testing

Revision ID: d9db00636711
Revises: 
Create Date: 2024-11-18 15:07:35.660509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9db00636711'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_statement_item')
    with op.batch_alter_table('financial_statement', schema=None) as batch_op:
        batch_op.drop_constraint('financial_statement_company_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'company', ['company_id'], ['original_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_statement', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('financial_statement_company_id_fkey', 'company', ['company_id'], ['id'])

    op.create_table('financial_statement_item',
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('financial_statement_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('noavaran_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('level_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('financial_statement_item_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
    sa.Column('statement_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['financial_statement_id'], ['financial_statement.id'], name='financial_statement_item_financial_statement_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='financial_statement_item_pkey')
    )
    # ### end Alembic commands ###
